export const INGREDIENTS = [
  // --- PROTEÍNAS ANIMAIS ---
  { en: "Chicken", pt: "Frango" },
  { en: "Chicken Breast", pt: "Peito de Frango" },
  { en: "Chicken Thighs", pt: "Coxa de Frango" },
  { en: "Chicken Wings", pt: "Asas de Frango" },
  { en: "Ground Beef", pt: "Carne Moída" },
  { en: "Beef Steak", pt: "Bife Bovino" },
  { en: "Pork", pt: "Carne Suína" },
  { en: "Pork Chops", pt: "Bisteca de Porco" },
  { en: "Bacon", pt: "Bacon" },
  { en: "Ham", pt: "Presunto" },
  { en: "Sausage", pt: "Linguiça" },
  { en: "Pepperoni", pt: "Pepperoni" },
  { en: "Salami", pt: "Salame" },
  { en: "Turkey", pt: "Peru" },
  { en: "Duck", pt: "Pato" },
  { en: "Lamb", pt: "Cordeiro" },
  { en: "Fish", pt: "Peixe" },
  { en: "Salmon", pt: "Salmão" },
  { en: "Tuna", pt: "Atum" },
  { en: "Cod", pt: "Bacalhau" },
  { en: "Tilapia", pt: "Tilápia" },
  { en: "Sardines", pt: "Sardinha" },
  { en: "Shrimp", pt: "Camarão" },
  { en: "Crab", pt: "Caranguejo" },
  { en: "Lobster", pt: "Lagosta" },
  { en: "Squid", pt: "Lula" },
  { en: "Octopus", pt: "Polvo" },
  { en: "Eggs", pt: "Ovos" },
  { en: "Quail Eggs", pt: "Ovos de Codorna" },

  // --- PROTEÍNAS VEGETAIS ---
  { en: "Tofu", pt: "Tofu" },
  { en: "Tempeh", pt: "Tempeh" },
  { en: "Seitan", pt: "Seitan" },
  { en: "Edamame", pt: "Edamame" },
  { en: "Textured Vegetable Protein", pt: "Proteína de Soja" },

  // --- LATICÍNIOS E SUBSTITUTOS ---
  { en: "Milk", pt: "Leite" },
  { en: "Almond Milk", pt: "Leite de Amêndoas" },
  { en: "Soy Milk", pt: "Leite de Soja" },
  { en: "Oat Milk", pt: "Leite de Aveia" },
  { en: "Coconut Milk", pt: "Leite de Coco" },
  { en: "Heavy Cream", pt: "Creme de Leite" },
  { en: "Sour Cream", pt: "Creme Azedo" },
  { en: "Whipped Cream", pt: "Chantilly" },
  { en: "Butter", pt: "Manteiga" },
  { en: "Ghee", pt: "Manteiga Ghee" },
  { en: "Yogurt", pt: "Iogurte" },
  { en: "Greek Yogurt", pt: "Iogurte Grego" },
  { en: "Cheese", pt: "Queijo" },
  { en: "Mozzarella Cheese", pt: "Queijo Muçarela" },
  { en: "Parmesan Cheese", pt: "Queijo Parmesão" },
  { en: "Cheddar Cheese", pt: "Queijo Cheddar" },
  { en: "Cream Cheese", pt: "Cream Cheese" },
  { en: "Ricotta", pt: "Ricota" },
  { en: "Cottage Cheese", pt: "Queijo Cottage" },
  { en: "Feta Cheese", pt: "Queijo Feta" },
  { en: "Brie", pt: "Queijo Brie" },
  { en: "Gorgonzola", pt: "Gorgonzola" },
  { en: "Provolone", pt: "Provolone" },
  { en: "Blue Cheese", pt: "Queijo Azul" },
  { en: "Goat Cheese", pt: "Queijo de Cabra" },

  // --- VEGETAIS E LEGUMES ---
  { en: "Tomato", pt: "Tomate" },
  { en: "Cherry Tomato", pt: "Tomate Cereja" },
  { en: "Onion", pt: "Cebola" },
  { en: "Red Onion", pt: "Cebola Roxa" },
  { en: "Garlic", pt: "Alho" },
  { en: "Potato", pt: "Batata" },
  { en: "Sweet Potato", pt: "Batata Doce" },
  { en: "Carrot", pt: "Cenoura" },
  { en: "Broccoli", pt: "Brócolis" },
  { en: "Cauliflower", pt: "Couve-flor" },
  { en: "Spinach", pt: "Espinafre" },
  { en: "Lettuce", pt: "Alface" },
  { en: "Arugula", pt: "Rúcula" },
  { en: "Kale", pt: "Couve" },
  { en: "Cabbage", pt: "Repolho" },
  { en: "Purple Cabbage", pt: "Repolho Roxo" },
  { en: "Cucumber", pt: "Pepino" },
  { en: "Bell Pepper", pt: "Pimentão" },
  { en: "Red Bell Pepper", pt: "Pimentão Vermelho" },
  { en: "Yellow Bell Pepper", pt: "Pimentão Amarelo" },
  { en: "Zucchini", pt: "Abobrinha" },
  { en: "Eggplant", pt: "Berinjela" },
  { en: "Pumpkin", pt: "Abóbora" },
  { en: "Butternut Squash", pt: "Abóbora Manteiga" },
  { en: "Mushrooms", pt: "Cogumelos" },
  { en: "Shiitake Mushrooms", pt: "Cogumelos Shiitake" },
  { en: "Portobello Mushrooms", pt: "Cogumelos Portobello" },
  { en: "Corn", pt: "Milho" },
  { en: "Peas", pt: "Ervilha" },
  { en: "Green Beans", pt: "Vagem" },
  { en: "Asparagus", pt: "Espargos" },
  { en: "Leek", pt: "Alho-poró" },
  { en: "Celery", pt: "Salsão" },
  { en: "Beetroot", pt: "Beterraba" },
  { en: "Radish", pt: "Rabanete" },
  { en: "Artichoke", pt: "Alcachofra" },
  { en: "Brussels Sprouts", pt: "Couve de Bruxelas" },
  { en: "Okra", pt: "Quiabo" },
  { en: "Cassava", pt: "Mandioca" },
  { en: "Yam", pt: "Inhame" },
  { en: "Chayote", pt: "Chuchu" },
  { en: "Fennel", pt: "Erva-doce (Bulbo)" },

  // --- FRUTAS ---
  { en: "Apple", pt: "Maçã" },
  { en: "Banana", pt: "Banana" },
  { en: "Orange", pt: "Laranja" },
  { en: "Lemon", pt: "Limão Siciliano" },
  { en: "Lime", pt: "Limão Taiti" },
  { en: "Strawberry", pt: "Morango" },
  { en: "Blueberry", pt: "Mirtilo" },
  { en: "Raspberry", pt: "Framboesa" },
  { en: "Blackberry", pt: "Amora" },
  { en: "Grape", pt: "Uva" },
  { en: "Pineapple", pt: "Abacaxi" },
  { en: "Mango", pt: "Manga" },
  { en: "Papaya", pt: "Mamão" },
  { en: "Watermelon", pt: "Melancia" },
  { en: "Melon", pt: "Melão" },
  { en: "Pear", pt: "Pera" },
  { en: "Peach", pt: "Pêssego" },
  { en: "Nectarine", pt: "Nectarina" },
  { en: "Plum", pt: "Ameixa" },
  { en: "Cherry", pt: "Cereja" },
  { en: "Avocado", pt: "Abacate" },
  { en: "Coconut", pt: "Coco" },
  { en: "Kiwi", pt: "Kiwi" },
  { en: "Passion Fruit", pt: "Maracujá" },
  { en: "Guava", pt: "Goiaba" },
  { en: "Fig", pt: "Figo" },
  { en: "Pomegranate", pt: "Romã" },
  { en: "Dates", pt: "Tâmaras" },
  { en: "Raisins", pt: "Uvas Passas" },
  { en: "Acai", pt: "Açaí" },

  // --- GRÃOS, CEREAIS E LEGUMINOSAS ---
  { en: "Rice", pt: "Arroz" },
  { en: "Brown Rice", pt: "Arroz Integral" },
  { en: "Basmati Rice", pt: "Arroz Basmati" },
  { en: "Arborio Rice", pt: "Arroz Arbóreo" },
  { en: "Pasta", pt: "Macarrão" },
  { en: "Spaghetti", pt: "Espaguete" },
  { en: "Penne", pt: "Penne" },
  { en: "Noodles", pt: "Macarrão Oriental" },
  { en: "Bread", pt: "Pão" },
  { en: "Whole Wheat Bread", pt: "Pão Integral" },
  { en: "Sourdough Bread", pt: "Pão de Fermentação Natural" },
  { en: "Baguette", pt: "Baguete" },
  { en: "Tortilla", pt: "Tortilha" },
  { en: "Beans", pt: "Feijão" },
  { en: "Black Beans", pt: "Feijão Preto" },
  { en: "White Beans", pt: "Feijão Branco" },
  { en: "Lentils", pt: "Lentilha" },
  { en: "Chickpeas", pt: "Grão de Bico" },
  { en: "Quinoa", pt: "Quinoa" },
  { en: "Oats", pt: "Aveia" },
  { en: "Granola", pt: "Granola" },
  { en: "Barley", pt: "Cevada" },
  { en: "Couscous", pt: "Cuscuz" },
  { en: "Cornmeal", pt: "Fubá" },
  { en: "Flour", pt: "Farinha de Trigo" },
  { en: "Whole Wheat Flour", pt: "Farinha Integral" },
  { en: "Almond Flour", pt: "Farinha de Amêndoas" },

  // --- ERVAS, ESPECIARIAS E TEMPEROS ---
  { en: "Salt", pt: "Sal" },
  { en: "Sea Salt", pt: "Sal Marinho" },
  { en: "Black Pepper", pt: "Pimenta do Reino" },
  { en: "White Pepper", pt: "Pimenta Branca" },
  { en: "Cayenne Pepper", pt: "Pimenta Caiena" },
  { en: "Chili Flakes", pt: "Pimenta Calabresa" },
  { en: "Paprika", pt: "Páprica" },
  { en: "Smoked Paprika", pt: "Páprica Defumada" },
  { en: "Cumin", pt: "Cominho" },
  { en: "Turmeric", pt: "Cúrcuma (Açafrão-da-terra)" },
  { en: "Curry Powder", pt: "Curry" },
  { en: "Cinnamon", pt: "Canela" },
  { en: "Nutmeg", pt: "Noz-moscada" },
  { en: "Cloves", pt: "Cravo" },
  { en: "Ginger Powder", pt: "Gengibre em Pó" },
  { en: "Fresh Ginger", pt: "Gengibre Fresco" },
  { en: "Garlic Powder", pt: "Alho em Pó" },
  { en: "Onion Powder", pt: "Cebola em Pó" },
  { en: "Oregano", pt: "Orégano" },
  { en: "Basil", pt: "Manjericão" },
  { en: "Parsley", pt: "Salsinha" },
  { en: "Cilantro", pt: "Coentro" },
  { en: "Rosemary", pt: "Alecrim" },
  { en: "Thyme", pt: "Tomilho" },
  { en: "Sage", pt: "Sálvia" },
  { en: "Mint", pt: "Hortelã" },
  { en: "Dill", pt: "Endro" },
  { en: "Bay Leaves", pt: "Louro" },
  { en: "Chives", pt: "Cebolinha" },
  { en: "Saffron", pt: "Açafrão" },
  { en: "Cardamom", pt: "Cardamomo" },
  { en: "Star Anise", pt: "Anis Estrelado" },
  { en: "Vanilla Extract", pt: "Extrato de Baunilha" },

  // --- ÓLEOS E CONDIMENTOS ---
  { en: "Olive Oil", pt: "Azeite de Oliva" },
  { en: "Vegetable Oil", pt: "Óleo Vegetal" },
  { en: "Canola Oil", pt: "Óleo de Canola" },
  { en: "Sunflower Oil", pt: "Óleo de Girassol" },
  { en: "Coconut Oil", pt: "Óleo de Coco" },
  { en: "Sesame Oil", pt: "Óleo de Gergelim" },
  { en: "Vinegar", pt: "Vinagre" },
  { en: "Apple Cider Vinegar", pt: "Vinagre de Maçã" },
  { en: "Balsamic Vinegar", pt: "Vinagre Balsâmico" },
  { en: "Soy Sauce", pt: "Molho Shoyu" },
  { en: "Worcestershire Sauce", pt: "Molho Inglês" },
  { en: "Hot Sauce", pt: "Molho de Pimenta" },
  { en: "Sriracha", pt: "Sriracha" },
  { en: "BBQ Sauce", pt: "Molho Barbecue" },
  { en: "Ketchup", pt: "Ketchup" },
  { en: "Mustard", pt: "Mostarda" },
  { en: "Dijon Mustard", pt: "Mostarda Dijon" },
  { en: "Mayonnaise", pt: "Maionese" },
  { en: "Tomato Paste", pt: "Extrato de Tomate" },
  { en: "Tomato Sauce", pt: "Molho de Tomate" },
  { en: "Pesto", pt: "Pesto" },
  { en: "Hummus", pt: "Homus" },
  { en: "Tahini", pt: "Tahine" },
  { en: "Miso", pt: "Missô" },

  // --- NOZES E SEMENTES ---
  { en: "Almonds", pt: "Amêndoas" },
  { en: "Walnuts", pt: "Nozes" },
  { en: "Cashews", pt: "Castanha de Caju" },
  { en: "Peanuts", pt: "Amendoim" },
  { en: "Brazil Nuts", pt: "Castanha do Pará" },
  { en: "Hazelnuts", pt: "Avelã" },
  { en: "Pistachios", pt: "Pistache" },
  { en: "Pecans", pt: "Noz Pecã" },
  { en: "Chia Seeds", pt: "Sementes de Chia" },
  { en: "Flaxseeds", pt: "Linhaça" },
  { en: "Sunflower Seeds", pt: "Sementes de Girassol" },
  { en: "Pumpkin Seeds", pt: "Sementes de Abóbora" },
  { en: "Sesame Seeds", pt: "Gergelim" },
  { en: "Pine Nuts", pt: "Pinoli" },

  // --- CONFEITARIA E ADOÇANTES ---
  { en: "Sugar", pt: "Açúcar" },
  { en: "Brown Sugar", pt: "Açúcar Mascavo" },
  { en: "Powdered Sugar", pt: "Açúcar de Confeiteiro" },
  { en: "Honey", pt: "Mel" },
  { en: "Maple Syrup", pt: "Xarope de Bordo (Maple)" },
  { en: "Agave Syrup", pt: "Xarope de Agave" },
  { en: "Molasses", pt: "Melaço" },
  { en: "Stevia", pt: "Stévia" },
  { en: "Chocolate", pt: "Chocolate" },
  { en: "Dark Chocolate", pt: "Chocolate Amargo" },
  { en: "Milk Chocolate", pt: "Chocolate ao Leite" },
  { en: "White Chocolate", pt: "Chocolate Branco" },
  { en: "Cocoa Powder", pt: "Cacau em Pó" },
  { en: "Chocolate Chips", pt: "Gotas de Chocolate" },
  { en: "Baking Powder", pt: "Fermento Químico" },
  { en: "Baking Soda", pt: "Bicarbonato de Sódio" },
  { en: "Yeast", pt: "Fermento Biológico" },
  { en: "Cornstarch", pt: "Amido de Milho" },
  { en: "Gelatin", pt: "Gelatina" },

  // --- OUTROS ---
  { en: "Water", pt: "Água" },
  { en: "Sparkling Water", pt: "Água com Gás" },
  { en: "Coffee", pt: "Café" },
  { en: "Tea", pt: "Chá" },
  { en: "Wine", pt: "Vinho" },
  { en: "Red Wine", pt: "Vinho Tinto" },
  { en: "White Wine", pt: "Vinho Branco" },
  { en: "Beer", pt: "Cerveja" },
  { en: "Ice", pt: "Gelo" },
  { en: "Stock/Broth", pt: "Caldo (Carne/Legumes)" }
];

export const TRANSLATIONS = {
  en: {
    appTitle: "Fridge Chef",
    dashboard: "Dashboard",
    myRecipes: "My Recipes",
    pantry: "Pantry",
    mealPlan: "Meal Plan",
    logout: "Logout",
    welcome: "Welcome back",
    generateRecipe: "Generate Recipe",
    yourIngredients: "Your Ingredients",
    preferences: "Preferences (optional)",
    addIngredient: "Add Ingredient",
    generating: "AI Chef is cooking...",
    saveRecipe: "Save Recipe",
    saving: "Saving...",
    viewFullRecipe: "View Full Recipe",
    delete: "Delete",
    cancel: "Cancel",
    share: "Share",
    makePrivate: "Make Private",
    addToMealPlan: "Add to Meal Plan",
    ingredients: "Ingredients",
    calories: "calories",
    searchIngredients: "Search ingredients...",
    searchRecipes: "Search recipes...",
    notFound: "No ingredient found.",
    selectIngredient: "Select ingredient",
    pantryTitle: "My Pantry",
    pantrySubtitle: "Manage your ingredients to get better recipe suggestions",
    addItem: "Add Item",
    quantity: "Quantity",
    add: "Add",
    recipeGeneratorTitle: "AI Recipe Generator",
    recipeGeneratorSubtitle: "Transform your fridge ingredients into delicious meals with AI",
    recipeSaved: "Recipe saved to your collection!",
    recipeDeleted: "Recipe deleted",
    itemAdded: "Item added to pantry",
    itemRemoved: "Item removed from pantry",
    addedToPlan: "Added to meal plan",
    removedFromPlan: "Removed from meal plan",
    shareSuccess: "Link copied to clipboard!",
    sharePrivate: "Recipe is now private",
    errorGeneric: "Something went wrong",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    name: "Name",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    loginButton: "Sign In",
    registerButton: "Sign Up",
    recipeNotFound: "Recipe Not Found",
    recipeNotFoundDesc: "Recipe not found or private",
    ingredientsUsed: "Ingredients Used",
    date: "Date",
    meal: "Meal",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snack",
    typeIngredient: "Type an ingredient...",
    scheduleMeal: "Schedule \"{recipe}\" for a meal.",
    deleteConfirm: "Are you sure you want to delete \"{recipe}\"? This action cannot be undone.",
    deleteTitle: "Delete Recipe",
    mealPlanTitle: "Add to Meal Plan",
    mySavedRecipes: "My Saved Recipes",
    mySavedRecipesSubtitle: "Your personal collection of AI-generated recipes",
    ingredient: "Ingredient",
    maxCalories: "Max Calories",
    filter: "Filter",
    noRecipesFound: "No recipes found",
    noRecipesFoundDesc: "Try adjusting your filters or generate a new recipe.",
    mealPlanHeader: "Meal Plan",
    mealPlanSubtitle: "Plan your week ahead.",
    previousWeek: "Previous Week",
    today: "Today",
    nextWeek: "Next Week",
    aiRecipeGenerator: "AI Recipe Generator",
    aiRecipeGeneratorSubtitle: "Transform your fridge ingredients into delicious meals with AI",
    pageNotFound: "Oops! Page not found",
    returnToHome: "Return to Home",
    loginSubtitle: "Sign in to continue your culinary journey",
    signingIn: "Signing in...",
    createOne: "Create one",
    joinApp: "Join Fridge Chef",
    registerSubtitle: "Create your account and start cooking with AI",
    username: "Username",
    confirmPassword: "Confirm Password",
    createAccount: "Create Account",
    creatingAccount: "Creating account...",
    accountCreated: "Account created successfully!",
    landingTitlePrefix: "Turn Your Ingredients Into",
    landingTitleSuffix: "Delicious Meals",
    landingSubtitle: "Let AI be your personal chef. Input what's in your fridge and get instant, creative recipes tailored to your ingredients.",
    startCooking: "Start Cooking with AI",
    featureAI: "AI-Powered",
    featureAIDesc: "Advanced AI generates creative recipes from your available ingredients",
    featureInstant: "Instant Results",
    featureInstantDesc: "Get complete recipes with instructions and calorie estimates in seconds",
    featureSave: "Save & Organize",
    featureSaveDesc: "Build your personal recipe collection and access it anytime",
    addIngredientError: "Please add at least one ingredient",
    recipeGeneratedSuccess: "Recipe generated successfully!",
    preferencesPlaceholder: "e.g., quick meal, low-carb, spicy...",
  },
  pt: {
    appTitle: "Chef de Geladeira",
    dashboard: "Início",
    myRecipes: "Minhas Receitas",
    pantry: "Despensa",
    mealPlan: "Planejamento",
    logout: "Sair",
    welcome: "Bem-vindo de volta",
    generateRecipe: "Gerar Receita",
    yourIngredients: "Seus Ingredientes",
    preferences: "Preferências (opcional)",
    addIngredient: "Adicionar Ingrediente",
    generating: "Chef IA está cozinhando...",
    saveRecipe: "Salvar Receita",
    saving: "Salvando...",
    viewFullRecipe: "Ver Receita Completa",
    delete: "Excluir",
    cancel: "Cancelar",
    share: "Compartilhar",
    makePrivate: "Tornar Privado",
    addToMealPlan: "Adicionar ao Planejamento",
    ingredients: "Ingredientes",
    calories: "calorias",
    searchIngredients: "Buscar ingredientes...",
    searchRecipes: "Buscar receitas...",
    notFound: "Nenhum ingrediente encontrado.",
    selectIngredient: "Selecionar ingrediente",
    pantryTitle: "Minha Despensa",
    pantrySubtitle: "Gerencie seus ingredientes para obter melhores sugestões",
    addItem: "Adicionar Item",
    quantity: "Quantidade",
    add: "Adicionar",
    recipeGeneratorTitle: "Gerador de Receitas IA",
    recipeGeneratorSubtitle: "Transforme os ingredientes da sua geladeira em refeições deliciosas com IA",
    recipeSaved: "Receita salva na sua coleção!",
    recipeDeleted: "Receita excluída",
    itemAdded: "Item adicionado à despensa",
    itemRemoved: "Item removido da despensa",
    addedToPlan: "Adicionado ao planejamento",
    removedFromPlan: "Removido do planejamento",
    shareSuccess: "Link copiado para a área de transferência!",
    sharePrivate: "Receita agora é privada",
    errorGeneric: "Algo deu errado",
    login: "Entrar",
    register: "Registrar",
    email: "Email",
    password: "Senha",
    name: "Nome",
    noAccount: "Não tem uma conta?",
    hasAccount: "Já tem uma conta?",
    loginButton: "Entrar",
    registerButton: "Cadastrar",
    recipeNotFound: "Receita Não Encontrada",
    recipeNotFoundDesc: "Receita não encontrada ou privada",
    ingredientsUsed: "Ingredientes Usados",
    date: "Data",
    meal: "Refeição",
    breakfast: "Café da Manhã",
    lunch: "Almoço",
    dinner: "Jantar",
    snack: "Lanche",
    typeIngredient: "Digite um ingrediente...",
    scheduleMeal: "Agendar \"{recipe}\" para uma refeição.",
    deleteConfirm: "Tem certeza que deseja excluir \"{recipe}\"? Esta ação não pode ser desfeita.",
    deleteTitle: "Excluir Receita",
    mealPlanTitle: "Adicionar ao Planejamento",
    mySavedRecipes: "Minhas Receitas Salvas",
    mySavedRecipesSubtitle: "Sua coleção pessoal de receitas geradas por IA",
    ingredient: "Ingrediente",
    maxCalories: "Máx. Calorias",
    filter: "Filtrar",
    noRecipesFound: "Nenhuma receita encontrada",
    noRecipesFoundDesc: "Tente ajustar seus filtros ou gere uma nova receita.",
    mealPlanHeader: "Planejamento de Refeições",
    mealPlanSubtitle: "Planeje sua semana com antecedência.",
    previousWeek: "Semana Anterior",
    today: "Hoje",
    nextWeek: "Próxima Semana",
    aiRecipeGenerator: "Gerador de Receitas IA",
    aiRecipeGeneratorSubtitle: "Transforme os ingredientes da sua geladeira em refeições deliciosas com IA",
    pageNotFound: "Ops! Página não encontrada",
    returnToHome: "Voltar para o Início",
    loginSubtitle: "Entre para continuar sua jornada culinária",
    signingIn: "Entrando...",
    createOne: "Criar uma",
    joinApp: "Junte-se ao Chef de Geladeira",
    registerSubtitle: "Crie sua conta e comece a cozinhar com IA",
    username: "Nome de Usuário",
    confirmPassword: "Confirmar Senha",
    createAccount: "Criar Conta",
    creatingAccount: "Criando conta...",
    accountCreated: "Conta criada com sucesso!",
    landingTitlePrefix: "Transforme Seus Ingredientes em",
    landingTitleSuffix: "Refeições Deliciosas",
    landingSubtitle: "Deixe a IA ser seu chef pessoal. Informe o que tem na geladeira e receba receitas criativas e instantâneas personalizadas para seus ingredientes.",
    startCooking: "Comece a Cozinhar com IA",
    featureAI: "IA Avançada",
    featureAIDesc: "IA avançada gera receitas criativas a partir dos seus ingredientes disponíveis",
    featureInstant: "Resultados Instantâneos",
    featureInstantDesc: "Receba receitas completas com instruções e estimativas de calorias em segundos",
    featureSave: "Salve e Organize",
    featureSaveDesc: "Construa sua coleção pessoal de receitas e acesse a qualquer momento",
    addIngredientError: "Por favor, adicione pelo menos um ingrediente",
    recipeGeneratedSuccess: "Receita gerada com sucesso!",
    preferencesPlaceholder: "ex: refeição rápida, low-carb, apimentado...",
  },
};
